# crd.yaml
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: myappconfigs.example.com
spec:
  group: example.com
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                greetingMessage:
                  type: string
  scope: Namespaced
  names:
    plural: myappconfigs
    singular: myappconfig
    kind: MyAppConfig
    shortNames:
    - ct