apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app-deployment
spec:  
  replicas: 2
  selector:
    matchLabels:
      app: demo-app
  template:  
    metadata:
      labels:
        app: demo-app
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
        prometheus.io/port: "80"
    spec:
      affinity:
       podAntiAffinity:
         requiredDuringSchedulingIgnoredDuringExecution:
           - labelSelector:
               matchExpressions:
                 - key: app
                   operator: In
                   values:
                     - demo-app
             topologyKey: "kubernetes.io/hostname"
      containers:
      - name: demo-app-container
        image: neslihanbukte/demo-app:latest
        ports:
        - containerPort: 5000
          name: http
