apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: demo-app-monitor
  namespace: monitoring  
  labels:
    release: kube-prometheus-stack  
spec:
  jobLabel: demo-app
  selector:
    matchLabels:
      app: demo-app  
  namespaceSelector:
    matchNames:
      - demo-ns
  endpoints:
    - port: http  
      path: /metrics
      interval: 15s
      
