prometheusOperator:
  admissionWebhooks:
    enabled: false

prometheus:
  prometheusSpec:
    additionalScrapeConfigs:
      - job_name: 'demo-app'
        metrics_path: /metrics
        static_configs:
          - targets: ['demo-app-service.default.svc.cluster.local:5000']

prometheusAdapter:
  enabled: true
  rules:
    default: false
    custom:
      - seriesQuery: 'demo_app_random_metric'
        resources:
          overrides:
            namespace:
              resource: "namespace"
            pod:
              resource: "pod"
        name:
          matches: "demo_app_random_metric"
          as: "demo_app_random_metric"
        metricsQuery: 'avg(demo_app_random_metric) by (pod)'