name: CI/CD Pipeline for Demo App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Reposoyu klonla
      uses: actions/checkout@v3

    - name: Docker’a login ol
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Docker image’ı build et
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/demo-app:${{ github.sha }} .

    - name: Docker image’ı push et
      run: docker push ${{ secrets.DOCKER_USERNAME }}/demo-app:${{ github.sha }}

    - name: Kubeconfig dosyasını oluştur
      run: |
        echo "${{ secrets.KUBECONFIG_BASE64 }}" | base64 -d > kubeconfig
        echo "KUBECONFIG=$PWD/kubeconfig" >> $GITHUB_ENV

    - name: Kubernetes deployment'ı image ile güncelle
      run: |
        kubectl set image deployment/demo-app-deployment demo-app-container=${{ secrets.DOCKER_USERNAME }}/demo-app:${{ github.sha }}
        kubectl rollout status deployment/demo-app-deployment
